site_name: JCDB
repo_url: https://github.com/finnmglas/jcdb/

site_description: The JSON Class Database (python module).
site_author: Finn M Glas

nav:
    - 'Introduction': 'index.md'

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - python
